import { execSync } from 'child_process';
import https from 'https';

export function parseGitHubUrl(url) {
  const clean = url.replace(/\/+$/, '');
  const regex = /^(?:https:\/\/github\.com\/|git@github\.com:)([^/]+)\/([^/]+?)(?:\.git)?$/;
  const match = clean.match(regex);
  if (match) {
    return { owner: match[1], repo: match[2] };
  }
  throw new Error(`Invalid GitHub URL: ${url}`);
}

export function cloneRepo(repoUrl, targetDir, pat) {
  try {
    let cloneUrl = repoUrl;
    if (pat && repoUrl.startsWith('https://')) {
      cloneUrl = repoUrl.replace('https://', `https://x-access-token:${pat}@`);
    } else if (pat && repoUrl.startsWith('git@')) {
      const { owner, repo } = parseGitHubUrl(repoUrl);
      cloneUrl = `https://x-access-token:${pat}@github.com/${owner}/${repo}.git`;
    }
    
    execSync(`git clone --depth 50 "${cloneUrl}" "${targetDir}"`, { stdio: 'pipe', timeout: 120000 });
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

export function createBranch(workdir, branchName) {
  try {
    execSync(`git checkout -B ${branchName}`, { cwd: workdir, timeout: 60000 });
  } catch (e) {
    execSync(`git checkout -b ${branchName}`, { cwd: workdir, timeout: 60000 });
  }
}

export function configureGit(workdir) {
  try {
    execSync(`git config user.name 'Swades Agent'`, { cwd: workdir, timeout: 60000 });
    execSync(`git config user.email 'swades@phonewhisper.ai'`, { cwd: workdir, timeout: 60000 });
  } catch (e) {}
}

export function commitAll(workdir, message) {
  try {
    execSync(`git add -A`, { cwd: workdir, timeout: 60000 });
    execSync(`git commit --allow-empty -m "${message.replace(/"/g, '\\"')}"`, { cwd: workdir, timeout: 60000 });
    return { success: true };
  } catch (e) {
    return { success: false, error: e.message };
  }
}

export function pushBranch(workdir, branchName, pat, repoUrl) {
  if (!pat) {
    console.log("No GitHub token provided. Skipping push.");
    return { success: false, error: "No GitHub token provided" };
  }
  
  let pushUrl = repoUrl;
  if (pat && repoUrl.startsWith('https://')) {
    pushUrl = repoUrl.replace('https://', `https://x-access-token:${pat}@`);
  } else if (pat && repoUrl.startsWith('git@')) {
    const { owner, repo } = parseGitHubUrl(repoUrl);
    pushUrl = `https://x-access-token:${pat}@github.com/${owner}/${repo}.git`;
  }
  
  try {
    execSync(`git push -u --force "${pushUrl}" "HEAD:${branchName}"`, { cwd: workdir, timeout: 90000, stdio: 'pipe' });
    return { success: true };
  } catch (err) {
    console.warn("Git push failed:", err.message);
    return { success: false, error: err.message };
  }
}

export function openPullRequest({ owner, repo, head, base, title, body, pat }) {
  return new Promise((resolve) => {
    if (!pat) {
      resolve({ pr_url: null, pr_number: null, error: "No GitHub authentication token" });
      return;
    }

    const payload = JSON.stringify({
      title: title || 'Swades Agent Update',
      body: body || 'Automated Pull Request generated by Swades Agent.',
      head: head,
      base: base || 'main'
    });

    const options = {
      hostname: 'api.github.com',
      port: 443,
      path: `/repos/${owner}/${repo}/pulls`,
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${pat}`,
        'User-Agent': 'SwadesAgent/1.0',
        'Accept': 'application/vnd.github+json',
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload)
      }
    };
    
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          if (res.statusCode >= 200 && res.statusCode < 300) {
            resolve({ pr_url: json.html_url, pr_number: json.number });
          } else {
            const errorMsg = json.errors ? json.errors.map(e => e.message).join(', ') : (json.message || `HTTP ${res.statusCode}`);
            resolve({ pr_url: null, pr_number: null, error: errorMsg });
          }
        } catch (e) {
          resolve({ pr_url: null, pr_number: null, error: `Parse error: ${e.message}` });
        }
      });
    });
    
    req.on('error', (err) => resolve({ pr_url: null, pr_number: null, error: err.message }));
    req.setTimeout(15000, () => {
      req.destroy();
      resolve({ pr_url: null, pr_number: null, error: "GitHub API request timed out" });
    });
    req.write(payload);
    req.end();
  });
}

export function getDefaultBranch({ owner, repo, pat }) {
  return new Promise((resolve) => {
    const headers = {
      'User-Agent': 'SwadesAgent/1.0',
      'Accept': 'application/vnd.github+json'
    };
    if (pat) headers['Authorization'] = `Bearer ${pat}`;
    
    const options = {
      hostname: 'api.github.com',
      port: 443,
      path: `/repos/${owner}/${repo}`,
      method: 'GET',
      headers: headers
    };
    
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          resolve(json.default_branch || 'main');
        } catch (e) {
          resolve('main');
        }
      });
    });
    
    req.on('error', () => resolve('main'));
    req.setTimeout(8000, () => {
      req.destroy();
      resolve('main');
    });
    req.end();
  });
}
